
[workspace]
members = [
    "math_utils",
    "data_utils",
    "graphics_utils",
    "car_sim",
    "car_game",
]

resolver = "2"


[package]
name = "car_rl"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
num-traits = "0.2.19"
macroquad = "0.4.14"
itertools = "0.14.0"
